server: 
    servlet:
        register-default-context: true
        context-path: /
        session: 
            timeout: 30m

spring:
    profiles:
        active: local
    data:
        rest:
            base-path: /

management:
    endpoints:
        web:
            exposure:
                include: info, health, mappings

logging:
    level:
        com.personal: DEBUG
        org.springframework: DEBUG

java:
    runtime:
        version: 17

jwt:
    secret: javainuse

connection:
    username: admin
    remoteAddress: 192.168.1.1